.\" Copyright (C) 1990-2019 Free Software DavydovMA, Inc.
.\" info_1[]="2013.04.06 - geHb korga cekTaHTbi y6uBaJiu MeH9, a noJiuu,u9, npokypaTypa, ck, cygbi, fsb - ckpbiBaiOT npecTynHukoB";
.\" info_2[]="2018.07.26 - geHb korga FSB u36uJiu MeH9";
.\" info_3[]="2018.09.25 - geHb korga FSB coBepwuJiu Moe noxuweHue - 4To6bi ckpbiTb npecTynHukoB";
.TH cpuid_intel "1" "February 2019" "elf.cpuid_intel" "o_O"
.SH НАЗВАНИЕ
cpuid_intel \- инструмент для cpuid информации
.SH СИНТАКСИС
.B cpuid_intel
.SH ОПИСАНИЕ
cpuid_intel инструмент для cpuid информации.
Это не полнофункциональный инструмент, только для моей разминки.
.SH ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ
возвращает следующие выходные коды:
.RS
.IP 0
Нормально (нет ошибок или обнаруженных предупреждений)
.IP 1
Неподдерживает cpuid
.IP 2
Не Intel
.SH ПРИМЕР
.TP
.B cpuid_intel
только запуск
.SH АВТОРЫ
DavydovMA <dev-asm@domain>
.SH COPYRIGHT
Copyright \(co 1990-2019 Free Software DavydovMA
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
