.\" Copyright (C) 1990-2019 Free Software DavydovMA, Inc.
.\" info_1[]="2013.04.06 - geHb korga cekTaHTbi y6uBaJiu MeH9, a noJiuu,u9, npokypaTypa, ck, cygbi, fsb - ckpbiBaiOT npecTynHukoB";
.\" info_2[]="2018.07.26 - geHb korga FSB u36uJiu MeH9";
.\" info_3[]="2018.09.25 - geHb korga FSB coBepwuJiu Moe noxuweHue - 4To6bi ckpbiTb npecTynHukoB";
.TH cpuid_intel "1" "February 2019" "elf.cpuid_intel" "o_O"
.SH NAME
cpuid_intel \- is utilite for cpuid info
.SH SYNOPSIS
.B cpuid_intel
.SH DESCRIPTION
cpuid_intel is utilite for cpuid info.
This is not full funcional, only for me example.
.SH DIAGNOSTICS
returns the following exit codes:
.RS
.IP 0
Normal (no errors or warnings detected)
.IP 1
Unsupported cpuid
.IP 2
Not Intel
.SH EXAMPLE
.TP
.B cpuid_intel
only run
.SH AUTHOR
DavydovMA <dev-asm@domain>
.SH COPYRIGHT
Copyright \(co 1990-2019 Free Software DavydovMA
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
